# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['photogeoalign.py'],
    pathex=[],
    binaries=[
        # Inclusion des binaires Open3D
        ('venv/lib/python3.*/site-packages/open3d/cpu/*.so', 'open3d/cpu/'),
        ('venv/lib/python3.*/site-packages/open3d/geometry/*.so', 'open3d/geometry/'),
        ('venv/lib/python3.*/site-packages/open3d/io/*.so', 'open3d/io/'),
        ('venv/lib/python3.*/site-packages/open3d/utility/*.so', 'open3d/utility/'),
        ('venv/lib/python3.*/site-packages/open3d/visualization/*.so', 'open3d/visualization/'),
    ],
    datas=[('resources/logo.png', '.')],
    hiddenimports=[
        'modules.core.utils',
        'modules.core.micmac', 
        'modules.core.geodetic',
        'modules.gui.main_window',
        'modules.gui.dialogs',
        'modules.workers.pipeline_thread',
        'modules.workers.geodetic_thread',
        'modules.workers.utils',
        'multiprocessing',
        'multiprocessing.pool',
        'multiprocessing.managers',
        'multiprocessing.synchronize',
        'multiprocessing.heap',
        'scipy._lib._ccallback_c',
        'scipy._cyutility',
        'scipy.interpolate._bsplines',
        'scipy.interpolate._fitpack',
        'scipy.interpolate._fitpack2',
        'scipy.sparse.csgraph._validation',
        'scipy.special._ufuncs_cxx',
        # Open3D imports critiques
        'open3d',
        'open3d.cpu',
        'open3d.cpu.pybind',
        'open3d.cpu.pybind.cpython-311-x86_64-linux-gnu',
        'open3d.cpu.pybind.cpython-311-x86_64-linux-gnu.so',
        'open3d.cpu.pybind.cpython-310-x86_64-linux-gnu',
        'open3d.cpu.pybind.cpython-310-x86_64-linux-gnu.so',
        'open3d.cpu.pybind.cpython-39-x86_64-linux-gnu',
        'open3d.cpu.pybind.cpython-39-x86_64-linux-gnu.so',
        # Autres dépendances Open3D
        'open3d.geometry',
        'open3d.io',
        'open3d.utility',
        'open3d.visualization'
    ],
    hookspath=['hooks'],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['PySide6.QtNetwork'],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='photogeoalign_linux',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['resources/logo.png'],
)