# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['photogeoalign.py'],
    pathex=[],
    binaries=[],
    datas=[('resources/logo.png', '.')],
    hiddenimports=[
        'modules.core.utils',
        'modules.core.micmac', 
        'modules.core.geodetic',
        'modules.gui.main_window',
        'modules.gui.dialogs',
        'modules.workers.pipeline_thread',
        'modules.workers.geodetic_thread',
        'modules.workers.utils',
        'multiprocessing',
        'multiprocessing.pool',
        'multiprocessing.managers',
        'multiprocessing.synchronize',
        'multiprocessing.heap',
        'scipy._lib._ccallback_c',
        'scipy._cyutility',
        'scipy.interpolate._bsplines',
        'scipy.interpolate._fitpack',
        'scipy.interpolate._fitpack2',
        'scipy.sparse.csgraph._validation',
        'scipy.special._ufuncs_cxx'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['PySide6.QtNetwork'],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='photogeoalign.exe',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['resources\\logo.png'],
)
